=== marcusAvreli/MyToolBox/windows/vbs/books/books.dtd
<!ELEMENT catalog    (book+) >
<!ELEMENT book       (author, title, genre, price, publish_date, description) >
<!ATTLIST book       id ID #REQUIRED >
<!ELEMENT author         (#PCDATA)   >
<!ELEMENT title          (#PCDATA)   >
<!ELEMENT genre          (#PCDATA)   >
<!ELEMENT price          (#PCDATA)   >
<!ELEMENT publish_date   (#PCDATA)   >
<!ELEMENT description    (#PCDATA)   >

=== marcusAvreli/MyToolBox/VB_Script/books/books-well-formed.xml
<?xml version="1.0"?>
<!DOCTYPE catalog PUBLIC "books.dtd" "books.dtd">
<catalog>
   <book id="bk101">
      <author>Gambardella, Matthew</author>
      <title>XML Developer's Guide</title>
      <genre>Computer</genre>
<!-- The following line is not valid according to books.dtd. -->
      <!--cost>44.95</cost-->
	  <price>44.95</price>
      <publish_date>2000-10-01</publish_date>
      <description>An in-depth look at creating applications with
      XML.</description>
   </book>
</catalog>
